language: cpp

os:
  - linux
  #- osx

compiler:
  - clang
  - gcc

script:
  - ./configure --prefix=$PWD/tempbuild --with-ssl --with-zlib --enable-bigfile && make && make install

branches:
  only:
  - master

notifications:
    slack: htdig:KJALZaL1b3jsXdVMir6cyTYI

    irc:
    channels:
      - "chat.freenode.net##hldig"
    skip_join: false
    use_notice: true
    on_success: change
    template:
      - "[%{repository_name}#%{branch}@%{commit}] %{author}: %{message} %{build_url}"
