script: ./configure --with-ssl --with-zlib --with-apache --enable-bigfile --enable-tests && make

# blocklist
#branches:
#  except:
#  - legacy
#  - experimental

# safelist
branches:
  only:
  - master

notifications:
    slack: htdig:KJALZaL1b3jsXdVMir6cyTYI
