script: ./configure --prefix=$PWD/tempbuild --with-ssl --with-zlib --enable-bigfile && make && make install

# blocklist
#branches:
#  except:
#  - legacy
#  - experimental

# safelist
branches:
  only:
  - master

notifications:
    slack: htdig:KJALZaL1b3jsXdVMir6cyTYI
