language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then xcode-select --install; fi
  - ./configure --prefix=$PWD/tempbuild --with-ssl --with-zlib --enable-bigfile && make && make install

allow_failures:
    - os: osx

# blocklist
#branches:
#  except:
#  - legacy
#  - experimental

# safelist
branches:
  only:
  - master

notifications:
    slack: htdig:KJALZaL1b3jsXdVMir6cyTYI
